# Generated by Django 5.1.6 on 2025-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text Only'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
